name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  # Allow read access to pull request for golangci-lint
  pull-requests: read
  # Allow write access to checks to allow the action to annotate code in the PR
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Fetch all history for proper SonarQube analysis
          fetch-depth: 0

      - name: Set up Go
        id: setup-go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Display Go version
        run: go version

      - name: go mod tidy (fails if changes are needed)
        run: go mod tidy --diff

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          cache-invalidation-interval: 30

      - name: Go test
        run: |
          go test -short -timeout 1m ./...
          # Run full test suite with coverage report
          go test -race -cover -coverprofile=unit.coverage.out -timeout 5m github.com/robbyt/go-loglater

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=robbyt_go-loglater
            -Dsonar.organization=robbyt
            -Dsonar.go.coverage.reportPaths=unit.coverage.out
            -Dsonar.sources=.
            -Dsonar.coverage.exclusions=examples/**/*
            -Dsonar.exclusions=**/*_test.go
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.language=go
            -Dsonar.sourceEncoding=UTF-8
